title: Gaston's GitHub Pages Site
description: Welcome to my personal website built with Jekyll and hosted on GitHub Pages
baseurl: "/gaston.github.io" # Project site subpath
url: "https://lunar-eclipse255.github.io" # GitHub user site root

# Theme - explicitly specify minima for GitHub Pages
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: right-sidebar

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
