title: Gaston's Website
description: My personal website built with Jekyll and GitHub Pages
url: "https://lunar-eclipse255.github.io/gaston.github.io/"
baseurl: ""
repository: Lunar-Eclipse255/gaston.github.io

# Theme
remote_theme: mmistakes/minimal-mistakes

# Theme configuration
minimal_mistakes_skin: "dark"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Garden-style sidebar navigation
sidebar:
  - home
  - about
  - label: Tutorials
    children:
      - getting-started
      - configuration
  - label: Reference
    children:
      - api-reference

# Build settings
markdown: kramdown
highlighter: rouge

sidebar:
  - home
  - about-me


# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
