title: Gaston's GitHub Pages Site
description: Welcome to my personal website built with Jekyll and hosted on GitHub Pages
baseurl: "" # No subpath for user site
url: "https://lunar-eclipse255.github.io" # GitHub user site root

# Use GitHub Pages compatible theme
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections for organized content
collections:
  guides:
    output: true
    permalink: /content/guides/:name/
  tutorials:
    output: true
    permalink: /content/tutorials/:name/
  reference:
    output: true
    permalink: /content/reference/:name/

# Default settings for different content types
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _templates/
