title: Gaston's Website
description: My personal website built with Jekyll and GitHub Pages
baseurl: ""       # your repo name
url: "https://lunar-eclipse255.github.io/gaston.github.io/"  # your GitHub Pages URL
repository: Lunar-Eclipse255/gaston.github.io

# Theme
remote_theme: pages-themes/cayman

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Garden-style sidebar navigation
sidebar:
  - home
  - about
  - label: Tutorials
    children:
      - getting-started
      - configuration
  - label: Reference
    children:
      - api-reference

# Build settings
markdown: kramdown
highlighter: rouge

sidebar:
  - home
  - about-me


# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
