title: Gaston's GitHub Pages Site
description: Welcome to my personal website built with Jekyll and hosted on GitHub Pages
baseurl: "/gaston.github.io" # Project site subpath
url: "https://lunar-eclipse255.github.io" # GitHub user site root

# Theme - explicitly specify minima for GitHub Pages
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections for organized content
collections:
  guides:
    output: true
    permalink: /content/guides/:name/
  tutorials:
    output: true
    permalink: /content/tutorials/:name/
  reference:
    output: true
    permalink: /content/reference/:name/

# Default settings for different content types
defaults:
  - scope:
      path: ""
    values:
      layout: right-sidebar
  - scope:
      path: "content/guides"
      type: "pages"
    values:
      layout: right-sidebar
      category: guide
  - scope:
      path: "content/tutorials"
      type: "pages"
    values:
      layout: right-sidebar
      category: tutorial
  - scope:
      path: "content/reference"
      type: "pages"
    values:
      layout: right-sidebar
      category: reference
  - scope:
      path: "content/blog"
      type: "pages"
    values:
      layout: right-sidebar
      category: blog

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _templates/
