title: Gaston's Website
description: My personal website built with Jekyll and GitHub Pages
url: "https://lunar-eclipse255.github.io/gaston.github.io/"
baseurl: ""

# Theme
remote_theme: zendesk/jekyll-theme-zendesk-garden

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
