title: Gaston's Website
description: My personal website built with Jekyll and GitHub Pages
url: "https://lunar-eclipse255.github.io/gaston.github.io/"
baseurl: ""
repository: Lunar-Eclipse255/gaston.github.io

# Theme
remote_theme: zendesk/jekyll-theme-zendesk-garden

# Theme configuration
color_scheme: dark

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Build settings
markdown: kramdown
highlighter: rouge

sidebar:
  - home
  - about-me


# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
